version: '3.8'

services:
  python_app:
    build: 
      context: ./python_app
    container_name: python_app
    networks:
      - app_network
    volumes:
      - ./python_app:/usr/src/app
      - ./pymatgen:/usr/local/lib/python3.9/site-packages/pymatgen
    command: python /usr/src/app/main.py
    depends_on:
      - mongodb
      - mysql

  mysql:
    build: 
      context: ./mysql
    platform: linux/x86_64
    container_name: mysql
    networks:
      - app_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./mysql_data:/var/lib/mysql

  mongodb:
    build: 
      context: ./mongodb
    container_name: mongodb
    networks:
      - app_network
    volumes:
      - ./mongodb_data:/data/db

networks:
  app_network:
    driver: bridge
